version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
