version: '3.8'
services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SERVER_PORT: 8080
    ports:
      - ${API_PORT:-8080}:8080
    depends_on:
      - database
      - postgres
    volumes:
      - ./app:/app

volumes:
  mysqldata: