spring:
  application:
    name: hyperativa
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update

env:
  secret: ${SECRET}
  salt: ${SALT}
  issuer: ${ISSUER}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    algorithm: ${ALGORITHM:PBEWithMD5AndDES}
    key-obtention-iterations: ${JASYPT_ITERATIONS:1000}
    pool-size: ${JASYPT_POOL_SIZE:1}
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    string-output-type: base64